### PR TITLE
Fix Missing doi Bug

### PR DESCRIPTION
**Pull request by terrymyc**
This PR fixes a bug introduced by #631. Missing doi in a dataset caused failure in starting reviewing.

### CODE REVIEW

**Review by J535D165 — CHANGES_REQUESTED** [review]
Thanks. It would be really useful to have a unit test for this such that we avoid this issue in the future.

**Comment by J535D165** [comment]
Can you also implement `publish_time` is the same way as `doi` is implemented?

**Comment by terrymyc** [comment]
> Can you also implement `publish_time` in the same way as `doi` is implemented?

Should we add `publish_time` to the [documentation](https://asreview.readthedocs.io/en/latest/intro/datasets.html#data-format)? This column name is ambiguous. I think we usually see `year` and `date` in a reference manager. And is it necessary to have `date` in a dataset?

**Review by J535D165 — APPROVED** [review]

**Comment by J535D165** [comment]
Thanks for the fix @terrymyc.

**Pull request merged**
