### PR TITLE
change name max sampling

### PR DESCRIPTION
**Pull request by Rensvandeschoot**
I propose to change the name 'max' in the front-end to 'certainty-based' so that it matches the paper and documentation. I did not change any of the labels, only the the wording in the dropdown menu.

### CODE REVIEW

**Comment by Rensvandeschoot** [comment]
@terrymyc Is uncertainty-based also available?

**Comment by Rensvandeschoot** [comment]
@terrymyc If you agree we should also update the text in the information pop-up (and we should delete the balancing strategy, because it cannot be changed in the front-end, right?).

**Review by J535D165 — APPROVED** [review]

**Comment by Rensvandeschoot** [comment]
@terrymyc  / @J535D165  We should not provide the option for mixed sampling in the front-end, more research is needed what the optimal balance is for this option. So I would prefer three options: certainty-based, uncertainty-based and random.

**Comment by terrymyc** [comment]
> @terrymyc If you agree we should also update the text in the information pop-up (and we should delete the balancing strategy, because it cannot be changed in the front-end, right?).

No, we should remove the balancing strategy mentioned in the help information.
@J535D165 Do we have an uncertainty-based strategy?

**Review by terrymyc — APPROVED** [review]

**Comment by J535D165** [comment]
Internal functions still make use of the word Max. We can change this, but it doesn't look urgent to me. 

Thanks, and let's forward the other discussions to new PRs.

**Pull request merged**
