### PR TITLE
Fix for simple Docker port issue

### PR DESCRIPTION
**Pull request by cskaandorp**
Fix simple docker

### CODE REVIEW

**Comment by cskaandorp** [comment]
The issue is fixed, but read on! In the unauthenticated docker container there is not much room for configuration. Normally port 5000 is used, also exposed in the Dockerfile. Bridging port 8080 to 5000 was a bad idea because the origin of the request is not 5000 anymore. But sometimes, especially as a developer, you want another port. Long story short: for an easy fix both front and backend must run on the same port (no origin config). That means the backend port must be configurable without a TOML file. I have added an env variable PORT in start_flask and also the possibility to set it in the Docker setup.

I have tested it. But please do it as well.

And then I ran into another issue! Running from Docker, on port 8080, while creating a project, after adding the dataset I get a blank screen if I want to add prior knowledge: TypeError: Cannot read properties of undefined (reading 'label') (in frontend)

**Comment by cskaandorp** [comment]
Fixed the frontend issue. Please have a go at it to make sure I have done it right.

**Comment by J535D165** [comment]
#1567 reports that #1570 might fix the issue.

**Comment by J535D165** [comment]
Thanks for the PR. #1570 fixed the issue, and the rest of it was fixed in 0f5d7a049828cdb9a4efa4388028053bedb92ea8. Credits to you @cskaandorp

**Pull request closed without merging**
