### PR TITLE
Deprecated lr. use learning_rate

### PR DESCRIPTION
**Pull request by JTeijema**

### CODE REVIEW

**Comment by J535D165** [comment]
Thanks for the PR. Can you add the minimal version (of tf?) to `setup.py`? See:

https://github.com/asreview/asreview/blob/c03eb4ba380cc817819abab78d8ee96bee340f4d/setup.py#L111-L124

**Comment by JTeijema** [comment]
I.. am not sure how I should be figuring out the minimal version hahaha

**Comment by J535D165** [comment]
It seems like this holds for the entire 2-series of TensorFlow. Maybe restrict ASReview to TensorFlow 2.

**Comment by J535D165** [comment]
Thanks! Fixed remark via PR #672.

**Pull request merged**
