### PR TITLE
Change workdir in Dockerfile

### PR DESCRIPTION
**Pull request by zoneout215**
Added 'WORKDIR /app' for the Makita templates' implementations through Docker

### CODE REVIEW

**Review by abelsiqueira — COMMENTED** [review]
Hi @zoneout215, some comments:

- Maybe it's better to change `ENV ASREVIEW_PATH=/app/project_folder`, so it is explicitly defined.
- Have you run the web app and the simulation after the change? Do they work normally?

**Comment by zoneout215** [comment]
@abelsiqueira I've only tested Makita templates by now. I'm gonna give an update as soon as I make the test for web interface and simulations

**Comment by zoneout215** [comment]
> @abelsiqueira I've only tested Makita templates by now, and they were running. I'm gonna give an update as soon as I make the test for web interface and simulations

By now I've tested following functionality on Unbuntu machine:
- Simulations runs via CLI and web interface
- Image plotting via CLI and web interface 
- Makita templates run via CLI


I was also able to build the image from the same Dockerfile on Mac, so I assume that on UNIX everything works fine. But I have encoutered this error building an image on my Winodows PC, but I don't know if I should start and Issue if image building is not assumed in the documentation: 

#8 294.4 npm ERR! A complete log of this run can be found in:
#8 294.4 npm ERR!     /root/.npm/_logs/2023-05-18T12_02_39_071Z-debug.log
#8 294.4 Traceback (most recent call last):
#8 294.4   File "setup.py", line 83, in <module>
#8 294.4     setup(
#8 294.4   File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
#8 294.4     return distutils.core.setup(**attrs)
#8 294.4   File "/usr/local/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
#8 294.4     return run_commands(dist)
#8 294.4   File "/usr/local/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
#8 294.4     dist.run_commands()
#8 294.4   File "/usr/local/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
#8 294.4     self.run_command(cmd)
#8 294.4   File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 1244, in run_command
#8 294.4     super().run_command(command)
#8 294.4   File "/usr/local/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
#8 294.4     cmd_obj.run()
#8 294.4   File "setup.py", line 74, in run
#8 294.4     subprocess.check_call("sh ./asreview/webapp/compile_assets.sh", shell=True)
#8 294.4   File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call
#8 294.4     raise CalledProcessError(retcode, cmd)
#8 294.4 subprocess.CalledProcessError: Command 'sh ./asreview/webapp/compile_assets.sh' returned non-zero exit status 254.

**Review by abelsiqueira — APPROVED** [review]
@zoneout215, thanks for the reported tests. This looks good to me.
Building the Docker image on Windows is not relevant to me, so I approve this PR.

**Review by J535D165 — APPROVED** [review]

**Comment by J535D165** [comment]
Thanks @zoneout215. Can you file an issue for the Windows problem?

**Comment by zoneout215** [comment]
@J535D165 I already did!

**Comment by J535D165** [comment]
Thanks, the issue is easy to solve and broader than only Docker for Windows.

**Pull request merged**
