### PR TITLE
Replace api layer figure

### PR DESCRIPTION
**Pull request by JTeijema**
Replaces the original API figure with a new transparent image.

### CODE REVIEW

**Comment by JTeijema** [comment]
afbeelding

**Comment by JTeijema** [comment]
One more change pending, I see some inconsistency in the image.

**Comment by JTeijema** [comment]
Thats better
afbeelding

**Comment by JTeijema** [comment]
I can change the text if necessary!

**Review by Rensvandeschoot — APPROVED** [review]

**Review by J535D165 — CHANGES_REQUESTED** [review]
Nice! Where can we (and the community) find the source files? If the source files aren't stored in this repo, it might be good to link to them in a ReStructuredText comment.

**Comment by J535D165** [comment]
Let's think a bit about the descriptions. I think we can improve them:

1. - Low-level API
   - Fully written in Python
   - Perfect for data scientists
2. - Command Line Interface
   - Simulate systematic reviews
   - Powerful extensions like visualisation
3. - REST API written in Flask
4. - User-friendly interface
   - Runs in web-browser
   - Local installation
5. - [keep the description as is]

**Comment by JTeijema** [comment]
afbeelding

**Comment by J535D165** [comment]
Very nice figure!

**Pull request merged**
