### PR TITLE
Replace deprecated utcnow() by now()

### PR DESCRIPTION
**Pull request by J535D165**

### CODE REVIEW

**Comment by J535D165** [comment]
Help is welcome to fix the broken tests. It's not directly clear to me how to resolve this.

**Comment by jteijema** [comment]
I think `token_created_at` changes from offset-aware to offset-naive due to the subtraction of a `timedelta` .

**Comment by jteijema** [comment]
```python
def test_token_validity(setup_teardown, subtract_time):
    subtract_hours, subtract_mins, validity = subtract_time
    user = crud.create_user(DB)
    user.set_token_data("secret", "salt")
    DB.session.commit()
    # verify we have 1 record
    assert crud.count_users() == 1

    # assert token is valid
    token = user.token
    token_created_at = user.token_created_at

    assert token_created_at.tzinfo is not None and token_created_at.tzinfo.utcoffset(token_created_at) is not None, "token_created_at must be offset-aware"
    assert user.token_valid(token), "Token should be valid"

    # now subtract hours
    new_token_created_time = token_created_at - timedelta(
        hours=subtract_hours, minutes=subtract_mins
    )
    # update token_created_at
    user.token_created_at = new_token_created_time

    # assert token validity
    assert token_created_at.tzinfo is not None and token_created_at.tzinfo.utcoffset(token_created_at) is not None, "token_created_at must be offset-aware"
    assert user.token_valid(token) == validity, f"Token should be {'valid' if validity else 'invalid'}"
```

FAILED asreview/webapp/tests/test_database_and_models/test_user_model.py::test_token_validity[subtract_time0] - AssertionError: token_created_at must be offset-aware
FAILED asreview/webapp/tests/test_database_and_models/test_user_model.py::test_token_validity[subtract_time1] - AssertionError: token_created_at must be offset-aware
FAILED asreview/webapp/tests/test_database_and_models/test_user_model.py::test_token_validity[subtract_time2] - AssertionError: token_created_at must be offset-aware
FAILED asreview/webapp/tests/test_database_and_models/test_user_model.py::test_token_validity[subtract_time3] - AssertionError: token_created_at must be offset-aware

**Comment by jteijema** [comment]
`token_created_at = Column(DateTime(timezone=True))` sadly doesn't do the trick.

**Pull request merged**
