### PR TITLE
Add line chart to statistics panel on project page

### PR DESCRIPTION
**Pull request by terrymyc**
A new line chart made by @SagevdBrand is implemented to the statistics panel on the project page. It compares the efficiency of finding relevant documents by ASReview against at random.

localhost_3000_(iPad) (1)
localhost_3000_(iPad)

### CODE REVIEW

**Comment by Rensvandeschoot** [comment]
Nice! This graph will be very helpful!! 
One question:
Should the random line not reach 38 inclusions after labelling 6000 papers instead of only 300?

**Comment by terrymyc** [comment]
> Should the random line not reach 38 inclusions after labeling 6000 papers instead of only 300?

I agree. It will look like this:

localhost_3000_(iPad)

**Comment by Rensvandeschoot** [comment]
Yes, indeed. So, after reading 177 papers at random you would have found only 1 relevant paper, but with active learning 38... impressive!
This graph really demonstrates the added value of active learning!!!

**Comment by Rensvandeschoot** [comment]
Should we add some information abouth these three graphs on rtd? And add a pop-up or hyperlink in the front--end?

**Comment by J535D165** [comment]
Sounds good. Let's start with some information on RTD. 
Let's brainstorm with @MartijnUX about displaying the info in the frontend. Let's add this in a new PR.

**Review by J535D165 — APPROVED** [review]

**Comment by J535D165** [comment]
Thank you so much @SagevdBrand and @terrymyc!

**Pull request merged**
