### PR TITLE
Improve contrast ratio

### PR DESCRIPTION
**Pull request by terrymyc**
In response to #362, this PR improves the contrast ratio according to [WCAG guidelines](https://webaim.org/blog/wcag-2-0-and-link-colors/) on several pages either in light or dark mode.

- [x] Links
- [x] Document texts in the Exploration Mode
- [x] Other places have brown texts with black background

image

image

image

### CODE REVIEW

**Comment by J535D165** [comment]
https://github.com/asreview/asreview/blob/71bd23606e5f36c8be96dbc5945d2734526145be/asreview/webapp/src/Components/ArticlePanel.js#L94

Let's set this to primary (delete it). Both for title and abstract. Don't know why we used secondary in the past.

**Comment by terrymyc** [comment]
> Let's set this to primary (delete it). Both for title and abstract. Don't know why we used secondary in the past.

Then the texts in the article panel will be purely black. You sure? The current contrast ratio of the grey texts against the white background is acceptable.

image

**Comment by J535D165** [comment]
I think it is 0.87 black isn't it? I really like it. It looks way better on my new laptop.

**Comment by J535D165** [comment]
Thanks!

**Pull request merged**
