### PR TITLE
Show keywords when available

### PR DESCRIPTION
**Pull request by J535D165**
image

### CODE REVIEW

**Comment by Rensvandeschoot** [comment]
Very nice!

What field of the RIS file format are you using as input?

**Comment by J535D165** [comment]
RIS will use `KW`.

**Comment by PeterLombaers** [comment]
I like the look of it! One thought I had was that if the screen is small or the abstract is long, the keywords won't be visible immediately. If they came before the abstract, they would always be visible. But they might also be distracting above the abstract, so I'm not sure if that would really be an improvement.

**Comment by J535D165** [comment]
True and thanks for the suggestion. I discussed this with Cathelijne, and she favored having them at the bottom. But maybe I can make a setting for this.

**Pull request merged**
