### PR TITLE
Print warning if record ids are not unique.

### PR DESCRIPTION
**Pull request by qubixes**
Create new index in that case.

### CODE REVIEW

**Comment by J535D165** [comment]
Good strategy. Can you make a unit test on this one as well?

**Comment by qubixes** [comment]
I'm not sure what I would test honestly. Even before the PR, it should work. It's just that this is more neat / error prone if at some point we use the record_id's.

**Comment by J535D165** [comment]
Test should show that a dataset with duplicate `record_id` values doesn't fail. Ideally, it shows somehow that it makes use of the index. It feels odd to me that it works at the moment with duplicate values btw.

**Comment by qubixes** [comment]
That's the point; nothing really makes use of it at the moment. Prior_idx is kind of the only thing...

**Review by J535D165 — APPROVED** [review]

**Comment by J535D165** [comment]
Thanks for the fix and test!

**Pull request merged**
