### PR TITLE
Fix dashboard stats value not JSON serializable

### PR DESCRIPTION
**Pull request by terrymyc**
This PR resolved the problem of getting dashboard stats for old projects and added a test.

### CODE REVIEW

**Comment by J535D165** [comment]
Given the reuse potential of `get_statistics`, I think it is better to change the returned types of that function. 

https://github.com/asreview/asreview/blob/137a7849fcf6dc295c965fea9833a58237e316c9/asreview/webapp/utils/project.py#L488-L494

I think the following will also solve the issue:

```python
n_included = int(sum(labels == 1))
 n_excluded = int(sum(labels == 0))
  
 if len(labels) > 0: 
     n_since_last_relevant = int(labels.tolist()[::-1].index(1))
 else: 
     n_since_last_relevant = 0 
```

**Comment by terrymyc** [comment]
> Given the reuse potential of `get_statistics`, I think it is better to change the returned types of that function.

Good point. Thanks!

**Review by J535D165 — APPROVED** [review]

**Comment by J535D165** [comment]
Thanks! Shall we add the test in another PR?

**Comment by J535D165** [comment]
Nice!

**Pull request merged**
