### PR TITLE
info added about the ordering of the export file

### PR DESCRIPTION
**Pull request by Rensvandeschoot**
@J535D165 is record_id also added to the export file? if so, we need to add this to the documentation as well

### CODE REVIEW

**Comment by J535D165** [comment]
Yes, it is.

**Comment by Rensvandeschoot** [comment]
@J535D165 and just to be sure: record_id is row number of the data as uploaded and starting at zero

**Comment by J535D165** [comment]
If present, the variable `record_id` contains the values of the `record_id` column. Otherwise, ASReview generates a new record_id, based on the row number and starting at 0.

**Review by J535D165 — APPROVED** [review]

**Comment by J535D165** [comment]
Thanks, nice contribution!

**Pull request merged**
