### PR TITLE
Fix bug in type_from_column_spec

### PR DESCRIPTION
**Pull request by rohitgarud**
Fixes bug in type_from_column_spec, which is used in _standardize_dataframe. The bug was in the variable names while unpacking the col_specs. Here column_spec_name should be the key and the data type should be the value.

### CODE REVIEW

**Comment by J535D165** [comment]
Interesting! Thanks for the contribution. 

I agree that the documentation is not in line with behavior and therefore this is a bug. 

What confuses me is the difference between the default implementation and the `column_spec` implementation. 
First:
https://github.com/asreview/asreview/blob/942f755368e71cd7abe77232a3cc292e98a66465/asreview/io/utils.py#L117-L120
Second:
https://github.com/asreview/asreview/blob/942f755368e71cd7abe77232a3cc292e98a66465/asreview/io/utils.py#L121-L124

The second accepts column specs in this format:

https://github.com/asreview/asreview/blob/942f755368e71cd7abe77232a3cc292e98a66465/asreview/config.py#L48-L65

A small refactor can align the two (where we replace the `column_spec` implementation with the default format). What do you think?

**Comment by rohitgarud** [comment]
Hi @J535D165, thank you for your quick response. I found this bug because I was trying to use the `type_from_column_spec` function. 
From what I understand, FIRST and SECOND can be achieved with a single function `type_from_column`, and `type_from_column_spec` is not at all necessary. If the users want to define custom column_specs (or definitions), they can use the same format as `COLUMN_DEFINITIONS` and use `type_from_column`

**Comment by J535D165** [comment]
Indeed! Sorry for the confusion. Interested in deprecating that function in our code base?

**Comment by rohitgarud** [comment]
Should I refactor the code and create a pull request? How w can go about it?

**Comment by J535D165** [comment]
Yes, you can refactor the code in this PR (no need to start a new one). I don't think there is a need to add a deprecation warning as this is not a public part of the API and you are probably the first one to use it ;) Internally, it is never used haha

**Comment by rohitgarud** [comment]
Yeah, I was thinking the same. I will refactor the code. Do you think any additional tests are needed or the current tests will suffice?

**Comment by J535D165** [comment]
Let me rerun. Looks like a timeout error. Nice refactor, everything looks good to me!

**Comment by rohitgarud** [comment]
Thank you..Passed all tests :) .. Will this change be available right away if I upgrade ASReview using pip?

**Comment by J535D165** [comment]
It was a pleasure to merge your first contribution to asreview core. Looking forward to colab in the future!

**Comment by J535D165** [comment]
The new version will not be available immediately, but I will create a new release soon.

**Comment by rohitgarud** [comment]
Thank you @J535D165 . I was my first ever contribution to a big open-source project. I am working on few things and plan to contribute to ASReview frequently in future as I see it as a great opportunity for me to learn. Thank you for your guidance.

**Pull request merged**
