### PR TITLE
Update images

### PR DESCRIPTION
**Pull request by terrymyc**
This PR updated images used in the root folder and in the `webapp` folder. Images that are no longer in use are removed. `.png` images are replaced by `.svg` images if available.

The following images used currently do not have `.svg` version in the artwork repository:
https://github.com/asreview/asreview-artwork/blob/master/ElasAdventures/Arrows/EPS/ArrowLeft.ai

https://github.com/asreview/asreview-artwork/blob/master/ElasAdventures/Arrows/EPS/ArrowStraightAhead.ai

https://github.com/asreview/asreview-artwork/blob/master/ElasAdventures/Balloons/IconBalloonsEPS.ai

https://github.com/asreview/asreview-artwork/blob/master/ElasAdventures/Academy/Elas_afstudeerhoedje.ai

https://github.com/asreview/asreview-artwork/blob/master/ElasAdventures/ElasPotter/ElasPotter.ai

### CODE REVIEW

**Comment by J535D165** [comment]
Here you go :) 

ArrowLeft
ArrowStraightAhead
IconBalloonsEPS
Elas_Grad
ElasPotter

**Comment by J535D165** [comment]
Here you go :) 

ArrowLeft
ArrowStraightAhead
IconBalloonsEPS
Elas_Grad
ElasPotter

**Comment by J535D165** [comment]
The XML file should be preserved for now (it's a draw.io file to render the flowchart with)

**Comment by terrymyc** [comment]
Thanks! Although the ElasBalloon is somehow mirrored, it is fine. I think the images in `docs` can be updated later along with the merge of documentation PR.

**Review by J535D165 — APPROVED** [review]

**Comment by J535D165** [comment]
Merci beaucoup!

**Comment by Rensvandeschoot** [comment]
Great work!!! I also added the files to the [art-work repo](https://github.com/asreview/asreview-artwork/tree/master/SVGicons/used-in-frontend)

**Pull request merged**
