### PR TITLE
Fix error handler in first iteration of model training

### PR DESCRIPTION
**Pull request by terrymyc**
This PR fixed the error handler in the first iteration of model training.

### CODE REVIEW

**Comment by J535D165** [comment]
Nice work. I will work on a review. 

Do we have a workflow or file to cause this error such that I can test?

**Comment by terrymyc** [comment]
Selecting `Embedding IDF` can trigger an error.

**Comment by J535D165** [comment]
Resolved conflict with #1098.

**Comment by J535D165** [comment]
Is there also a chip for projects with errors on the project overview page?

**Comment by terrymyc** [comment]
No status chip for `error`. If a project's status is error, it is still in setup. Continuing the setup will clear the error.

**Review by J535D165 — APPROVED** [review]

**Pull request merged**
