### PR TITLE
Update cli.py format algorithm with extension detection

### PR DESCRIPTION
**Pull request by jteijema**
Following https://github.com/asreview/asreview-nemo/pull/7/, lets identify algorithms that are not in core.

### CODE REVIEW

**Comment by J535D165** [comment]
Very nice!

Maybe we can use `packages_distributions()[x.value.split(':')[0]]`. Then it doesn't matter what the name of the internal module is. The package name is in the lead then. See https://stackoverflow.com/a/78645825

**Comment by jteijema** [comment]
```
> asreview algorithms
Available active learning algorithms for ASReview.

  feature_extraction  Available feature extraction algorithms:

                      onehot
                      tfidf
                      doc2vec         ASReview-NEMO
                      labse           ASReview-NEMO
                      mxbai           ASReview-NEMO
                      sbert           ASReview-NEMO

  classifiers         Available classification algorithms:

                      logistic
                      nb
                      rf
                      svm
                      adaboost        ASReview-NEMO
                      dynamic-nn      ASReview-NEMO
                      nn-2-layer      ASReview-NEMO
                      xgboost         ASReview-NEMO
```

With the new implementation, I prefer this solution @J535D165 but I'm not happy with the base_module extraction voodoo.

**Comment by jteijema** [comment]
@J535D165 I like this implementation, its close to __main__'s implementation

**Comment by J535D165** [comment]
Nice. I'm happy with this implementation, including the version. Make sure you format the version in the same way as the main implementation. 

Happy to merge soon!

**Comment by jteijema** [comment]
```
\GitHub\asreview-nemo> asreview algorithms
Available active learning algorithms for ASReview.

  feature_extraction  Available feature extraction algorithms:

                      onehot
                      tfidf
                      doc2vec         [ASReview-NEMO 0.1.dev89+g835e3ac.d20241212]
                      labse           [ASReview-NEMO 0.1.dev89+g835e3ac.d20241212]
                      mxbai           [ASReview-NEMO 0.1.dev89+g835e3ac.d20241212]
                      sbert           [ASReview-NEMO 0.1.dev89+g835e3ac.d20241212]

  classifiers         Available classification algorithms:

                      logistic
                      nb
                      rf
                      svm
                      adaboost        [ASReview-NEMO 0.1.dev89+g835e3ac.d20241212]
                      dynamic-nn      [ASReview-NEMO 0.1.dev89+g835e3ac.d20241212]
                      nn-2-layer      [ASReview-NEMO 0.1.dev89+g835e3ac.d20241212]
                      xgboost         [ASReview-NEMO 0.1.dev89+g835e3ac.d20241212]

  query_strategies    Available query strategies:

                      cluster
                      max
                      max_random
                      max_uncertainty
                      random
                      uncertainty

  balance_strategies  Available balance strategies:

                      double
                      undersample

\GitHub\asreview-nemo> asreview -v
usage: asreview [-h] [-V] [subcommand]

ASReview LAB - A tool for AI-assisted systematic reviews

positional arguments:
  subcommand     The subcommand to launch. Available commands:


                 [asreview 2.0a4] - ASReview LAB - A tool for AI-assisted systematic reviews
                        algorithms
                        auth-tool
                        lab
                        simulate

                 [ASReview-NEMO 0.1.dev89+g835e3ac.d20241212] - ASReview New Exciting Models
                        nemo
```

**Review by J535D165 — APPROVED** [review]
5 very useful lines of code! Thanks

**Pull request merged**
