### PR TITLE
Make tests and setup.py Windows OS compatible

### PR DESCRIPTION
**Pull request by cskaandorp**
Some tests are failing on Windows OS. Here's a possible solution for that problem.

### CODE REVIEW

**Comment by J535D165** [comment]
Maybe good to setup a matrix for the different platforms https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs

**Comment by cskaandorp** [comment]
If all tests are green on Windows please do not merge yet. I'd like to try the OS matrix.

**Comment by PeterLombaers** [comment]
@J535D165 This also fixes a bug in `setup.py` where Windows users could not use `setup.py compile_assets`.

**Comment by J535D165** [comment]
Superb

**Pull request merged**
