### PR TITLE
Fix creating project with name in non-alphabetic language

### PR DESCRIPTION
**Pull request by terrymyc**
This PR fixes an issue with project id generation failing for non-alphabetic languages.

### CODE REVIEW

**Comment by J535D165** [comment]
Can you provide an example to test with. I think your change now breaks for project names with characters that are not allowed for Windows or POSIX file names. For example, what happens with `my?project`? 

https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file

**Comment by terrymyc** [comment]
@J535D165 Thanks for the reminder. You are right. I changed the regular expression to detect invalid file name characters.

**Comment by J535D165** [comment]
I think using https://tedboy.github.io/flask/generated/werkzeug.secure_filename.html might be a good solution. This is already used by asreview. 

Double question mark is interesting, but maybe not a priority. Only dashes is rare I think.

**Review by J535D165 — APPROVED** [review]

**Comment by J535D165** [comment]
Thanks @terrymyc, nice teamwork on this one.

**Pull request merged**
