### PR TITLE
Update footer to current year

### PR DESCRIPTION
**Pull request by JTeijema**
This PR fixes the documentation footer to show the current year instead of 2020.

### CODE REVIEW

**Comment by JTeijema** [comment]
image

**Review by J535D165 — APPROVED** [review]

**Review by VeenDuco — COMMENTED** [review]
Should it not be a range of years, see for instance a discussion [here](https://opensource.stackexchange.com/questions/2872/why-does-the-fsf-make-this-recommendation-about-ranges-of-copyright-years) or [scikit-learn docs](https://scikit-learn.org/stable/user_guide.html).

**Comment by JTeijema** [comment]
> Should it not be a range of years, see for instance a discussion [here](https://opensource.stackexchange.com/questions/2872/why-does-the-fsf-make-this-recommendation-about-ranges-of-copyright-years) or [scikit-learn docs](https://scikit-learn.org/stable/user_guide.html).

@J535D165

**Comment by J535D165** [comment]
Thanks for the feedback. Sounds good to me, but let's implement this for all files at the same time then.

**Comment by VeenDuco** [comment]
See here for a discussion: https://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated

Bottom line: It's not needed. It helps to establish a claim, but in principle copyright holds for the life of the author plus 70 years in Europe. If you do mention a date, the first date of the document is relevant to leave there because it helps establish timelines. Otherwise if someone copies your materials, you update your date to a year later, it makes it harder to see you had the materials first.

**Pull request merged**
